#!/usr/bin/env python
"""
Comprehensive Analysis for Taiwan P. League+ Basketball - June 16, 2026
========================================================================
Matchup: Fubon Braves (Home) vs Taoyuan Pilots (Away)

Running through MultiSportPredict pipeline with advanced basketball metrics,
FIBA-style analysis, and sharp consensus integration.
"""

import sys
import json
import math
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

# Import core confidence engine
from core.confidence_engine import confidence_score, bet_recommendation


def sigmoid(x: float) -> float:
    x = max(-500, min(500, x))
    return 1 / (1 + math.exp(-x))


def clamp(x: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, x))


def color_score(x) -> float:
    return {"green": 1.0, "yellow": 0.0, "red": -1.0}.get(str(x).strip().lower(), 0.0)


def normal_prob_above(mean: float, threshold: float, std_dev: float = 12.0) -> float:
    """Approximate probability of total exceeding threshold using normal distribution"""
    # Simple sigmoid-based approximation for normal CDF
    z = (threshold - mean) / std_dev
    return clamp(1 - sigmoid(z * 1.7))


# ============================================================================
# TAIWAN P. LEAGUE+ TEAM PROFILES
# ============================================================================

TEAM_PROFILES = {
    "Fubon Braves": {
        "abbreviation": "FUB",
        "ortg": 114.5,           # Points per 100 possessions
        "drtg": 106.8,           # Points allowed per 100 possessions
        "net_rating": 7.7,       # ORTG - DRTG
        "pace": 76.0,            # PLG pace per 40 min (slower than Euro/NBA)
        "points_per_game": 87.0,
        "points_allowed_per_game": 81.0,
        "three_pt_pct": 0.368,
        "two_pt_pct": 0.521,
        "ft_pct": 0.782,
        "rebounds_per_game": 42.5,
        "assists_per_game": 21.8,
        "turnovers_per_game": 12.5,
        "steals_per_game": 8.2,
        "blocks_per_game": 3.5,
        "home_record": 0.72,
        "away_record": 0.58,
        "recent_form": 0.65,     # Win % last 10 games
        "vs_opponent_record": 0.62,
        "rest_days": 3,
        "rotation_depth": 10,
        "injury_status": "green",
        "coach_stability": "green",
        "motivation": "green",
        "home_split_edge": 3.5,
        "three_pt_attempts_per_game": 28.5,
        "notes": "Defending PLG champions. Elite offensive efficiency with strong three-point shooting and ball movement. Deep rotation with consistent home dominance."
    },
    "Taoyuan Pilots": {
        "abbreviation": "TAO",
        "ortg": 110.2,
        "drtg": 110.5,
        "net_rating": -0.3,
        "pace": 74.0,
        "points_per_game": 83.0,
        "points_allowed_per_game": 85.0,
        "three_pt_pct": 0.342,
        "two_pt_pct": 0.498,
        "ft_pct": 0.755,
        "rebounds_per_game": 40.2,
        "assists_per_game": 19.5,
        "turnovers_per_game": 13.2,
        "steals_per_game": 7.5,
        "blocks_per_game": 3.0,
        "home_record": 0.55,
        "away_record": 0.42,
        "recent_form": 0.45,     # Win % last 10 games
        "vs_opponent_record": 0.38,
        "rest_days": 2,
        "rotation_depth": 9,
        "injury_status": "yellow",
        "coach_stability": "green",
        "motivation": "yellow",
        "home_split_edge": 2.0,
        "three_pt_attempts_per_game": 26.8,
        "notes": "Mid-tier PLG team. Defensive inefficiencies offset decent offensive production. Rebounding disadvantage against elite teams. Inconsistent on the road."
    },
}

# Venue configuration
VENUE_INFO = {
    "Taipei Heping Basketball Gymnasium": {
        "description": "Home venue of Fubon Braves. Capacity ~7,000. Indoor arena with consistent environment.",
        "home_boost_factor": 1.05,
        "notes": "Braves have strong home-court advantage here."
    }
}


def analyze_basketball_matchup(
    home_team: str,
    away_team: str,
    venue: str,
    date: str = "2026-06-16",
    market_spread: float = -6.5,
    market_total: float = 170.5,
    analysis_data: Dict[str, Any] = None,
) -> Dict[str, Any]:
    """
    Comprehensive analysis for a Taiwan P. League+ basketball match.
    """
    home_stats = TEAM_PROFILES[home_team]
    away_stats = TEAM_PROFILES[away_team]
    venue_info = VENUE_INFO.get(venue, {})

    generation_time = datetime.now().strftime("%Y-%m-%d %H:%M")
    print("=" * 85)
    print(f"TAIWAN P. LEAGUE+ MATCH ANALYSIS: {away_team} @ {home_team}")
    print(f"Date: {date}")
    print(f"Venue: {venue} | {venue_info.get('description', '')}")
    print("Generated by MultiSportPredict Engine")
    print(f"Timestamp: {generation_time}")
    print("=" * 85)
    print()

    # ── 1. TEAM STATISTICS ──
    print("1. TEAM STATISTICS (Advanced Metrics)")
    print("-" * 50)
    for label, stats in [(f"  {home_team} (Home):", home_stats), (f"  {away_team} (Away):", away_stats)]:
        print(label)
        print(f"    ORTG: {stats['ortg']:.1f} | DRTG: {stats['drtg']:.1f} | Net: {stats['net_rating']:+.1f}")
        print(f"    Pace: {stats['pace']:.1f} | PPG: {stats['points_per_game']:.1f} | PAPG: {stats['points_allowed_per_game']:.1f}")
        print(f"    3PT%: {stats['three_pt_pct']:.1%} | 2PT%: {stats['two_pt_pct']:.1%} | FT%: {stats['ft_pct']:.1%}")
        print(f"    REB: {stats['rebounds_per_game']:.1f} | AST: {stats['assists_per_game']:.1f} | TOV: {stats['turnovers_per_game']:.1f}")
        print(f"    Recent Form: {stats['recent_form']:.0%} | Home/Away: {stats['home_record']:.0%}/{stats['away_record']:.0%}")
        print(f"    Rest Days: {stats['rest_days']} | Rotation Depth: {stats['rotation_depth']}")
        print(f"    Notes: {stats['notes']}")
        print()

    # ── 2. EFFICIENCY ANALYSIS ──
    print("2. EFFICIENCY & MATCHUP ANALYSIS")
    print("-" * 50)
    
    # Net rating gap
    net_gap = home_stats['net_rating'] - away_stats['net_rating']
    ortg_gap = home_stats['ortg'] - away_stats['ortg']
    drtg_gap = away_stats['drtg'] - home_stats['drtg']  # Positive means home defense better
    
    # Pace analysis
    pace_avg = (home_stats['pace'] + away_stats['pace']) / 2
    
    # Rest and travel advantage
    home_rest_adv = (home_stats['rest_days'] - away_stats['rest_days']) * 1.5
    
    # Home/away split advantage
    split_adv = home_stats['home_split_edge'] - away_stats['home_split_edge']
    
    # Three-point edge
    three_pt_edge = (home_stats['three_pt_pct'] - away_stats['three_pt_pct']) * 20
    
    # Turnover edge
    tov_edge = (away_stats['turnovers_per_game'] - home_stats['turnovers_per_game']) * 1.5
    
    print(f"    Net Rating Gap: {net_gap:+.1f} (Favors {home_team if net_gap > 0 else away_team})")
    print(f"    ORTG Gap: {ortg_gap:+.1f} | DRTG Gap: {drtg_gap:+.1f}")
    print(f"    Pace: {pace_avg:.1f} possessions/40min")
    print(f"    Rest Advantage: {home_rest_adv:+.1f} (Favors {home_team if home_rest_adv > 0 else away_team})")
    print(f"    Home/Away Split Edge: {split_adv:+.1f}")
    print(f"    3PT Edge: {three_pt_edge:+.1f}")
    print(f"    Turnover Edge: {tov_edge:+.1f}")
    print()

    # ── 3. POINT PROJECTIONS ──
    print("3. POINT PROJECTIONS (Model-Based)")
    print("-" * 50)

    # Base projections using efficiency metrics
    home_base = (home_stats['ortg'] * pace_avg / 100) * venue_info.get('home_boost_factor', 1.0)
    away_base = (away_stats['ortg'] * pace_avg / 100) * 0.97  # Road adjustment
    
    # Adjust for rest, splits, and pace
    home_adj = (home_rest_adv + split_adv + three_pt_edge + tov_edge) * 0.5
    home_proj = home_base + home_adj
    away_proj = away_base - home_adj * 0.6  # Away team partially offset
    
    # Apply recent form adjustment
    home_form_factor = (0.85 + home_stats['recent_form'] * 0.30)
    away_form_factor = (0.85 + away_stats['recent_form'] * 0.30)
    home_proj *= home_form_factor
    away_proj *= away_form_factor
    
    total_proj = home_proj + away_proj
    spread_proj = home_proj - away_proj

    print(f"    {home_team} Projected Points: {home_proj:.1f}")
    print(f"    {away_team} Projected Points: {away_proj:.1f}")
    print(f"    Projected Total: {total_proj:.1f}")
    print(f"    Projected Spread: {spread_proj:+.1f}")
    print()

    # ── 4. TOTALS ANALYSIS (Normal Distribution) ──
    print("4. TOTALS ANALYSIS (Normal Distribution)")
    print("-" * 50)
    
    # Calculate over probabilities at key lines using normal approximation
    p_over_155 = normal_prob_above(total_proj, 155.5)
    p_over_160 = normal_prob_above(total_proj, 160.5)
    p_over_165 = normal_prob_above(total_proj, 165.5)
    p_over_170 = normal_prob_above(total_proj, 170.5)
    p_over_175 = normal_prob_above(total_proj, 175.5)
    
    print(f"    Over 155.5: {p_over_155:.1%}")
    print(f"    Over 160.5: {p_over_160:.1%}")
    print(f"    Over 165.5: {p_over_165:.1%}")
    print(f"    Over 170.5: {p_over_170:.1%}")
    print(f"    Over 175.5: {p_over_175:.1%}")

    totals_edge = total_proj - market_total
    total_conf = confidence_score(totals_edge, volatility=0.40)
    total_lean = "Over" if total_proj > market_total else "Under"
    
    # Determine over probability at market line
    if market_total <= 155.5:
        totals_prob = p_over_155
    elif market_total <= 160.5:
        totals_prob = p_over_160
    elif market_total <= 165.5:
        totals_prob = p_over_165
    elif market_total <= 170.5:
        totals_prob = p_over_170
    else:
        totals_prob = p_over_175
        
    if totals_prob >= 0.57:
        total_rec = f"Over {market_total}"
    elif totals_prob <= 0.43:
        total_rec = f"Under {market_total}"
    else:
        total_rec = "Pass"
    
    print(f"    Market Total: {market_total}")
    print(f"    Model Total: {total_proj:.1f}")
    print(f"    Edge: {totals_edge:+.1f}")
    print(f"    Lean: {total_lean} (Conf: {total_conf:.1f}%)")
    print(f"    Recommendation: {total_rec}")
    print()

    # ── 5. SPREAD ANALYSIS ──
    print("5. SPREAD ANALYSIS")
    print("-" * 50)
    
    spread_edge = spread_proj - market_spread
    
    # Calculate cover probability using normal distribution approximation
    std_dev_spread = 10.0  # Typical basketball spread std dev
    z_score = spread_edge / std_dev_spread
    cover_prob = clamp(sigmoid(z_score * 2.0))
    
    spread_conf = confidence_score(abs(spread_edge), volatility=0.35)
    
    if cover_prob >= 0.57:
        if spread_edge > 0:
            spread_rec = f"{home_team} -{abs(market_spread):.1f}"
        else:
            spread_rec = f"{away_team} +{abs(market_spread):.1f}"
    else:
        spread_rec = "Pass"
    
    print(f"    Model Spread: {spread_proj:+.1f} ({home_team} perspective)")
    print(f"    Market Line: {market_spread}")
    print(f"    Edge: {spread_edge:+.1f}")
    print(f"    Cover Probability: {cover_prob:.1%}")
    print(f"    Confidence: {spread_conf:.1f}%")
    print(f"    Recommendation: {spread_rec}")
    print()

    # ── 6. WIN PROBABILITY ──
    print("6. WIN PROBABILITY")
    print("-" * 50)
    
    # Win probability based on net rating gap with home court boost
    home_win_raw = sigmoid(net_gap * 0.15 + 0.35)  # 0.35 = home court baseline
    home_win_prob = clamp(home_win_raw * 0.85 + 0.10)
    away_win_prob = clamp(1 - home_win_prob)
    
    ml_edge = (home_win_prob - 0.5) * 100
    ml_conf = confidence_score(abs(ml_edge), volatility=0.40)
    ml_rec = "Pass"
    if home_win_prob >= 0.63:
        ml_rec = f"Moneyline {home_team} (Strong)"
    elif home_win_prob >= 0.57:
        ml_rec = f"Moneyline {home_team}"
    elif away_win_prob >= 0.63:
        ml_rec = f"Moneyline {away_team} (Strong)"
    elif away_win_prob >= 0.57:
        ml_rec = f"Moneyline {away_team}"
    
    print(f"    {home_team} Win Probability: {home_win_prob:.1%}")
    print(f"    {away_team} Win Probability: {away_win_prob:.1%}")
    print(f"    ML Edge: {ml_edge:+.1f}%")
    print(f"    Confidence: {ml_conf:.1f}%")
    print(f"    Recommendation: {ml_rec}")
    print()

    # ── 7. SHARP CONSENSUS ──
    print("7. SHARP CONSENSUS & MARKET LEAN")
    print("-" * 50)
    if analysis_data:
        for key, value in analysis_data.items():
            if key == "sharp_lean":
                print(f"    MARKET LEAN: {value}")
            elif key == "prop_angle":
                print(f"    PROP ANGLE: {value}")
            else:
                print(f"    {key.upper()}: {value}")
    print()

    # ── 8. PLAYER PROPS ──
    print("8. PLAYER PROPS PROJECTIONS")
    print("-" * 50)
    
    # Star player projections (simplified)
    home_star_pts_proj = home_stats['points_per_game'] * 0.28  # ~28% of team scoring
    away_star_pts_proj = away_stats['points_per_game'] * 0.30
    
    # Three-point props
    home_team_3pt_proj = home_stats['three_pt_attempts_per_game'] * home_stats['three_pt_pct']
    away_team_3pt_proj = away_stats['three_pt_attempts_per_game'] * away_stats['three_pt_pct']
    
    print(f"    {home_team} Star Player Points: {home_star_pts_proj:.1f} (Line: 12.5)")
    print(f"    {away_team} Star Player Points: {away_star_pts_proj:.1f} (Line: 11.5)")
    print(f"    {home_team} Team 3PT Made: {home_team_3pt_proj:.1f} (Line: 9.5)")
    print(f"    {away_team} Team 3PT Made: {away_team_3pt_proj:.1f} (Line: 8.5)")
    
    if analysis_data and "prop_angle" in analysis_data:
        print(f"    KEY PROP: {analysis_data['prop_angle']}")
    print()

    # ── 9. FINAL RECOMMENDATIONS ──
    print("9. FINAL RECOMMENDATIONS")
    print("-" * 50)
    print(f"    SPREAD ({market_spread:+.1f}): {spread_rec}")
    print(f"    TOTAL (O/U {market_total}): {total_rec} (Conf: {total_conf:.1f}%)")
    print(f"    MONEYLINE: {ml_rec} (Conf: {ml_conf:.1f}%)")
    print(f"    PROJECTED: {home_team} {home_proj:.1f} - {away_team} {away_proj:.1f}")
    print(f"    WIN PROB: {home_team} {home_win_prob:.1%} | {away_team} {away_win_prob:.1%}")
    if analysis_data and "sharp_lean" in analysis_data:
        print(f"    SHARP LEAN: {analysis_data['sharp_lean']}")
    print()
    print("=" * 85)

    # Build result dict
    result = {
        "sport": "basketball",
        "league": "P. League+ (Taiwan)",
        "matchup": f"{away_team} @ {home_team}",
        "venue": venue,
        "date": date,
        "generated_at": generation_time,
        "home_team": {
            "name": home_team,
            "abbreviation": home_stats["abbreviation"],
            "stats": home_stats,
        },
        "away_team": {
            "name": away_team,
            "abbreviation": away_stats["abbreviation"],
            "stats": away_stats,
        },
        "projections": {
            "home_points": round(home_proj, 1),
            "away_points": round(away_proj, 1),
            "total_points": round(total_proj, 1),
            "spread": round(spread_proj, 1),
        },
        "projection_details": {
            "net_rating_gap": round(net_gap, 1),
            "ortg_gap": round(ortg_gap, 1),
            "drtg_gap": round(drtg_gap, 1),
            "pace": round(pace_avg, 1),
            "rest_advantage": round(home_rest_adv, 1),
            "three_pt_edge": round(three_pt_edge, 1),
            "turnover_edge": round(tov_edge, 1),
        },
        "win_probability": {
            "home_prob": round(home_win_prob, 4),
            "away_prob": round(away_win_prob, 4),
        },
        "spread_analysis": {
            "model_spread": round(spread_proj, 1),
            "market_line": market_spread,
            "edge": round(spread_edge, 1),
            "cover_probability": round(cover_prob, 4),
            "confidence": round(spread_conf, 1),
            "recommendation": spread_rec,
        },
        "totals_analysis": {
            "model_total": round(total_proj, 1),
            "market_total": market_total,
            "edge": round(totals_edge, 1),
            "over_probability": round(totals_prob, 4),
            "confidence": round(total_conf, 1),
            "recommendation": total_rec,
            "lean": total_lean,
        },
        "moneyline_analysis": {
            "home_win_prob": round(home_win_prob, 4),
            "away_win_prob": round(away_win_prob, 4),
            "edge": round(ml_edge, 1),
            "confidence": round(ml_conf, 1),
            "recommendation": ml_rec,
        },
        "sharp_consensus": analysis_data or {},
        "player_props": {
            "home_star_points": round(home_star_pts_proj, 1),
            "away_star_points": round(away_star_pts_proj, 1),
            "home_team_3pt_made": round(home_team_3pt_proj, 1),
            "away_team_3pt_made": round(away_team_3pt_proj, 1),
        },
    }

    return result


def main():
    output_dir = Path("output/basketball")
    output_dir.mkdir(parents=True, exist_ok=True)

    # ──────────────────────────────────────────────────────────────────────
    # MATCHUP: Fubon Braves (Home) vs Taoyuan Pilots (Away)
    # Venue: Taipei Heping Basketball Gymnasium
    # League: P. League+ (Taiwan)
    # ──────────────────────────────────────────────────────────────────────
    print("\n" + "=" * 100)
    print("TAIWAN P. LEAGUE+: Fubon Braves vs Taoyuan Pilots")
    print("=" * 100)

    analysis_data = {
        "sharp_lean": "Fubon Braves -6.5 (Spread)",
        "prop_angle": "Fubon Star Player - Over Points (Pilots lack defensive stopper, Braves offense clicking at home)",
        "venue": "Taipei Heping Basketball Gymnasium",
        "league_notes": "P. League+ (Taiwan) - 4th season. Fubon Braves are back-to-back champions.",
        "keyMatchup": "Fubon's elite ORTG (114.5) vs Pilots' below-average DRTG (110.5). Braves should control pace.",
        "homeCourt": "Fubon has best home record in PLG (72%). Pilots struggle on road (42%).",
        "fatigueFactor": "Fubon has 3 days rest vs Pilots' 2. No travel issues - both based in Taipei area.",
        "sharpReasoning": "Fubon dominates this matchup historically (62%). Championship pedigree + home court + significant efficiency gap make Braves a strong play.",
    }

    result = analyze_basketball_matchup(
        home_team="Fubon Braves",
        away_team="Taoyuan Pilots",
        venue="Taipei Heping Basketball Gymnasium",
        date="2026-06-16",
        market_spread=-6.5,
        market_total=170.5,
        analysis_data=analysis_data,
    )

    # Save to file
    out_path = output_dir / "fubon_braves_vs_taoyuan_pilots_analysis.json"
    with open(out_path, 'w') as f:
        json.dump(result, f, indent=2, default=str)
    print(f"\nResults saved to: {out_path}")

    # ──────────────────────────────────────────────────────────────────────
    # SUMMARY
    # ──────────────────────────────────────────────────────────────────────
    print("\n\n" + "=" * 100)
    print("TAIWAN P. LEAGUE+ - JUNE 16, 2026 ANALYSIS SUMMARY")
    print("=" * 100)
    print()
    r = result
    print(f"MATCHUP: {r['away_team']['name']} @ {r['home_team']['name']}")
    print(f"    Projected: {r['away_team']['name']} {r['projections']['away_points']:.1f} @ {r['home_team']['name']} {r['projections']['home_points']:.1f}")
    print(f"    Total Proj: {r['projections']['total_points']:.1f} | Spread Proj: {r['projections']['spread']:+.1f}")
    print(f"    Win Prob: {r['home_team']['name']} {r['win_probability']['home_prob']:.1%} | "
          f"{r['away_team']['name']} {r['win_probability']['away_prob']:.1%}")
    print()
    print(f"    SPREAD: {r['spread_analysis']['recommendation']} (Conf: {r['spread_analysis']['confidence']:.1f}%)")
    print(f"    TOTAL: {r['totals_analysis']['recommendation']} (Conf: {r['totals_analysis']['confidence']:.1f}%)")
    print(f"    MONEYLINE: {r['moneyline_analysis']['recommendation']} (Conf: {r['moneyline_analysis']['confidence']:.1f}%)")
    print(f"    SHARP LEAN: {r['sharp_consensus']['sharp_lean']}")
    print()
    print("=" * 100)


if __name__ == "__main__":
    main()