#!/usr/bin/env python
"""
Comprehensive Analysis for FIFA World Cup - Jordan vs Algeria
===============================================================
Runs the World Cup xG + Poisson model and pushes a summary to Discord.

This script is intentionally standalone (no dependency on other World Cup scripts)
and uses the existing Discord webhook integration in `discord_integration.py`
(via `universal_runner.push_to_discord` compatibility wrapper).
"""

import json
import math
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional

from core.confidence_engine import confidence_score


def sigmoid(x: float) -> float:
    x = max(-500, min(500, x))
    return 1 / (1 + math.exp(-x))


def clamp(x: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, x))


def poisson_pmf(k: int, lam: float) -> float:
    """Poisson probability mass function."""
    if lam <= 0:
        return 0.0 if k > 0 else 1.0
    if k < 0:
        return 0.0
    try:
        log_pmf = -lam + k * math.log(lam) - math.lgamma(k + 1)
        return math.exp(log_pmf)
    except (ValueError, OverflowError):
        return 0.0


def poisson_over_prob(lam: float, line: float) -> float:
    """Probability of over a given line using Poisson."""
    n = int(math.floor(line))
    return 1 - sum(poisson_pmf(k, lam) for k in range(0, n + 1))


def poisson_at_least_one(lam: float) -> float:
    """Probability of at least one goal."""
    return 1 - math.exp(-lam)


# -----------------------------------------------------------------------------
# TEAM PROFILES - FIFA World Cup 2026 (heuristic placeholders)
# -----------------------------------------------------------------------------
# NOTE: The repo’s existing World Cup example hard-codes team profiles.
# Since Jordan/Algeria profiles are not present in code, these are calibrated
# to realistic mid-tier xG/defensive envelopes for a World Cup setting.
TEAM_PROFILES: Dict[str, Dict[str, Any]] = {
    "Jordan": {
        "abbreviation": "JOR",
        "xg_for": 1.35,
        "xg_against": 1.30,
        "shots_per_game": 12.5,
        "sot_per_game": 4.0,
        "goals_for_per_game": 1.25,
        "goals_against_per_game": 1.20,
        "clean_sheets_last10": 2,
        "home_record": 0.52,
        "away_record": 0.48,
        "recent_form": 0.50,
        "tempo": 0.55,
        "width_crossing": 0.52,
        "final_third_pressure": 0.58,
        "missing_attacker": 0,
        "missing_creator": 1,
        "missing_cb": 0,
        "missing_gk": 0,
        "fifa_ranking": 86,
        "star_power": 0.60,
        "notes": "Technically improving side with decent structure. Missing a key creator reduces chance quality; relies on compact defending and set-piece moments.",
    },
    "Algeria": {
        "abbreviation": "ALG",
        "xg_for": 1.45,
        "xg_against": 1.25,
        "shots_per_game": 13.0,
        "sot_per_game": 4.3,
        "goals_for_per_game": 1.30,
        "goals_against_per_game": 1.15,
        "clean_sheets_last10": 3,
        "home_record": 0.55,
        "away_record": 0.50,
        "recent_form": 0.52,
        "tempo": 0.58,
        "width_crossing": 0.55,
        "final_third_pressure": 0.60,
        "missing_attacker": 0,
        "missing_creator": 0,
        "missing_cb": 1,
        "missing_gk": 0,
        "fifa_ranking": 38,
        "star_power": 0.65,
        "notes": "Mid-tier talent with better shot volume than expected. One defensive absence can open transitions, but overall chance creation remains more stable than Jordan.",
    },
}

LEAGUE_CONFIG = {
    "avg_goals_per_game": 2.50,
    "goal_variance": 0.95,  # World Cup typically slightly lower scoring
    "home_advantage": 0.00,  # neutral venue
    "draw_rate": 0.28,
    "is_neutral_venue": True,
}


def analyze_worldcup_match(
    home_team: str,
    away_team: str,
    venue: str,
    date: str = "2026-06-16",
    market_total: float = 2.5,
    analysis_data: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    home_stats = TEAM_PROFILES[home_team]
    away_stats = TEAM_PROFILES[away_team]

    generation_time = datetime.now().strftime("%Y-%m-%d %H:%M")

    print("=" * 85)
    print(f"FIFA WORLD CUP 2026 MATCH ANALYSIS: {home_team} vs {away_team}")
    print(f"Date: {date}")
    print(f"Venue: {venue}")
    print(f"Generated by MultiSportPredict Engine")
    print(f"Timestamp: {generation_time}")
    print("=" * 85)
    print()

    # 1) xG-based lambda estimates
    home_lam = (
        0.55 * home_stats["xg_for"]
        + 0.30 * away_stats["xg_against"]
        + 0.15 * home_stats["sot_per_game"] / 4.0
        + 0.10 * home_stats["tempo"]
        + 0.05 * 0.0
        - 0.15 * home_stats["missing_attacker"]
        - 0.10 * home_stats["missing_creator"]
        + 0.12 * (away_stats["missing_cb"] + away_stats["missing_gk"])
    )
    home_lam *= LEAGUE_CONFIG["goal_variance"]

    away_lam = (
        0.55 * away_stats["xg_for"]
        + 0.30 * home_stats["xg_against"]
        + 0.15 * away_stats["sot_per_game"] / 4.0
        + 0.10 * away_stats["tempo"]
        + 0.05 * 0.0
        - 0.15 * away_stats["missing_attacker"]
        - 0.10 * away_stats["missing_creator"]
        + 0.12 * (home_stats["missing_cb"] + home_stats["missing_gk"])
    )
    away_lam *= LEAGUE_CONFIG["goal_variance"]

    total_lam = home_lam + away_lam

    # 2) outcome probabilities
    max_goals = 6
    home_win_prob = 0.0
    draw_prob = 0.0
    away_win_prob = 0.0

    for i in range(max_goals + 1):
        for j in range(max_goals + 1):
            p = poisson_pmf(i, home_lam) * poisson_pmf(j, away_lam)
            if i > j:
                home_win_prob += p
            elif i == j:
                draw_prob += p
            else:
                away_win_prob += p

    total_prob = home_win_prob + draw_prob + away_win_prob
    if total_prob > 0:
        home_win_prob /= total_prob
        draw_prob /= total_prob
        away_win_prob /= total_prob

    # draw rate adjustment
    draw_prob = draw_prob * 0.75 + LEAGUE_CONFIG["draw_rate"] * 0.25
    remaining = 1 - draw_prob
    denom = home_win_prob + away_win_prob + 0.001
    home_win_prob = home_win_prob * remaining / denom
    away_win_prob = 1 - home_win_prob - draw_prob

    # 3) total line probabilities
    p_over_15 = poisson_over_prob(total_lam, 1.5)
    p_over_25 = poisson_over_prob(total_lam, 2.5)
    p_over_35 = poisson_over_prob(total_lam, 3.5)

    totals_edge = total_lam - market_total

    total_conf = confidence_score(totals_edge, volatility=0.50)
    total_lean = "Over" if totals_edge > 0 else "Under"

    if market_total <= 1.5:
        totals_prob = p_over_15
    elif market_total <= 2.5:
        totals_prob = p_over_25
    else:
        totals_prob = p_over_35

    if totals_prob >= 0.57:
        total_rec = f"Over {market_total}"
    elif totals_prob <= 0.43:
        total_rec = f"Under {market_total}"
    else:
        total_rec = "Pass"

    # 4) BTTS approximation
    home_scores_prob = poisson_at_least_one(home_lam)
    away_scores_prob = poisson_at_least_one(away_lam)
    btts_prob_raw = home_scores_prob * away_scores_prob

    home_btts = (
        1.05 * (home_stats["xg_for"] - 1.20)
        + 0.95 * (home_stats["xg_against"] - 1.25)
        + 0.10 * (home_stats["goals_for_per_game"] - 1.2)
        + 0.10 * (home_stats["goals_against_per_game"] - 1.1)
        + 0.12 * (home_stats["sot_per_game"] - 3.5)
        + 0.18 * home_stats["tempo"]
        + 0.15 * home_stats["final_third_pressure"]
        - 0.35 * home_stats["missing_attacker"]
        + 0.28 * (home_stats["missing_cb"] + home_stats["missing_gk"])
        - 0.20 * home_stats["clean_sheets_last10"] / 10.0
    )
    away_btts = (
        1.05 * (away_stats["xg_for"] - 1.20)
        + 0.95 * (away_stats["xg_against"] - 1.25)
        + 0.10 * (away_stats["goals_for_per_game"] - 1.2)
        + 0.10 * (away_stats["goals_against_per_game"] - 1.1)
        + 0.12 * (away_stats["sot_per_game"] - 3.5)
        + 0.18 * away_stats["tempo"]
        + 0.15 * away_stats["final_third_pressure"]
        - 0.35 * away_stats["missing_attacker"]
        + 0.28 * (away_stats["missing_cb"] + away_stats["missing_gk"])
        - 0.20 * away_stats["clean_sheets_last10"] / 10.0
    )

    structural = sigmoid((home_btts + away_btts) / 2.0)
    btts_prob = clamp(0.45 * structural + 0.55 * btts_prob_raw)

    btts_edge = btts_prob - 0.5
    btts_edge_scaled = (btts_edge * 100.0) / 10.0
    btts_conf = confidence_score(btts_edge_scaled, volatility=0.48)

    btts_rec = "Yes BTTS" if btts_prob >= 0.57 else ("No BTTS" if btts_prob <= 0.43 else "Pass")

    # confidence for moneyline style recommendation (simple scaling)
    ml_edge_pct = abs(home_win_prob - 0.5) * 100
    ml_edge_scaled = ml_edge_pct / 10.0
    ml_conf = confidence_score(ml_edge_scaled, volatility=0.45)
    if home_win_prob >= 0.57:
        ml_rec = f"Moneyline {home_team}"
    elif away_win_prob >= 0.57:
        ml_rec = f"Moneyline {away_team}"
    else:
        ml_rec = "Pass (consider Double Chance)"

    print(f"    Projected Score: {home_team} {home_lam:.1f} - {away_team} {away_lam:.1f}")
    print(f"    Total xG: {total_lam:.2f}")
    print(f"    Win Prob: {home_team} {home_win_prob:.1%} | Draw {draw_prob:.1%} | {away_team} {away_win_prob:.1%}")
    print(f"    TOTAL: {total_rec} (Conf: {total_conf:.1f}%)")
    print(f"    BTTS: {btts_rec} (Conf: {btts_conf:.1f}%)")
    print(f"    MATCH OUTCOME: {ml_rec} (Conf: {ml_conf:.1f}%)")
    if analysis_data and "sharp_lean" in analysis_data:
        print(f"    SHARP LEAN: {analysis_data['sharp_lean']}")
    print()
    print("=" * 85)

    return {
        "sport": "soccer",
        "league": "FIFA World Cup 2026",
        "matchup": f"{home_team} vs {away_team}",
        "venue": venue,
        "date": date,
        "generated_at": generation_time,
        "home_team": {"name": home_team, "stats": home_stats},
        "away_team": {"name": away_team, "stats": away_stats},
        "projections": {
            "home_xg": round(home_lam, 2),
            "away_xg": round(away_lam, 2),
            "total_xg": round(total_lam, 2),
            "home_projected_goals": round(home_lam, 1),
            "away_projected_goals": round(away_lam, 1),
        },
        "match_outcome": {
            "home_win_prob": round(home_win_prob, 4),
            "draw_prob": round(draw_prob, 4),
            "away_win_prob": round(away_win_prob, 4),
            "ml_rec": ml_rec,
            "ml_confidence": round(ml_conf, 1),
        },
        "totals_analysis": {
            "model_total": round(total_lam, 2),
            "market_total": market_total,
            "edge": round(totals_edge, 2),
            "over_probability": round(p_over_25, 4),
            "confidence": round(total_conf, 1),
            "recommendation": total_rec,
            "lean": total_lean,
        },
        "btts_analysis": {
            "probability": round(btts_prob, 4),
            "edge": round(btts_edge, 4),
            "confidence": round(btts_conf, 1),
            "recommendation": btts_rec,
        },
        "sharp_consensus": analysis_data or {},
    }


def push_worldcup_to_discord(result: Dict[str, Any], webhook_url: Optional[str] = None) -> bool:
    # Use universal_runner wrapper (it maps to discord_integration.push_to_discord).
    from universal_runner import push_to_discord

    sport = "soccer"
    home = result["home_team"]["name"]
    away = result["away_team"]["name"]

    market_total = float(result["totals_analysis"]["market_total"])
    projected_total = float(result["totals_analysis"]["model_total"])
    edge = f"{float(result['totals_analysis']['edge']):+.2f}"
    recommendation = str(result["totals_analysis"]["recommendation"])
    confidence = float(result["totals_analysis"]["confidence"])

    extra_metrics = (
        f"Win Prob: {home} {result['match_outcome']['home_win_prob']*100:.1f}% | "
        f"Draw {result['match_outcome']['draw_prob']*100:.1f}% | "
        f"{away} {result['match_outcome']['away_win_prob']*100:.1f}%\n"
        f"BTTS: {result['btts_analysis']['recommendation']} ({result['btts_analysis']['confidence']:.1f}%)\n"
        f"BTTS Prob: {result['btts_analysis']['probability']*100:.1f}%"
    )

    # If webhook_url not provided, universal_runner/disc_integration will read DISCORD_WEBHOOK_URL from env.
    return push_to_discord(
        sport=sport,
        home=home,
        away=away,
        market_total=market_total,
        projected_total=projected_total,
        edge=edge,
        recommendation=recommendation,
        confidence=confidence,
        webhook_url=webhook_url,
        extra_metrics=extra_metrics,
    )


def main() -> None:
    output_dir = Path("output/soccer")
    output_dir.mkdir(parents=True, exist_ok=True)

    home_team = "Jordan"
    away_team = "Algeria"
    venue = "World Cup 2026 - Neutral Venue"
    date = "2026-06-16"
    market_total = 2.5

    analysis_data = {
        "sharp_lean": "Algeria +0.00 (Preview) — Slight edge via more stable chance creation",
        "venue": venue,
        "keyMatchup": "Jordan chance-quality dip vs Algeria shot volume; neutral venue increases draw likelihood.",
        "rankGap": f"Jordan vs Algeria (heuristic FIFA ranks used: {TEAM_PROFILES['Jordan']['fifa_ranking']} vs {TEAM_PROFILES['Algeria']['fifa_ranking']})",
    }

    result = analyze_worldcup_match(
        home_team=home_team,
        away_team=away_team,
        venue=venue,
        date=date,
        market_total=market_total,
        analysis_data=analysis_data,
    )

    out_path = output_dir / "jordan_vs_algeria_worldcup_analysis.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, default=str)
    print(f"\nResults saved to: {out_path}")

    # Push to Discord (best-effort; requires DISCORD_WEBHOOK_URL and requests installed)
    webhook = os.getenv("DISCORD_WEBHOOK_URL")
    ok = push_worldcup_to_discord(result, webhook_url=webhook)
    if ok:
        print("✓ Discord webhook: pushed Jordan vs Algeria result successfully.")
    else:
        print("✗ Discord webhook: push failed (check DISCORD_WEBHOOK_URL / requests installation).")


if __name__ == "__main__":
    main()
