#!/usr/bin/env python
"""
Comprehensive Analysis for Estonian Meistriliiga Soccer - June 16, 2026
========================================================================
Matchup: FC Kuressaare vs Trans Narva

Running through MultiSportPredict pipeline with xG-based analysis,
Poisson goal modeling, and sharp consensus integration.
"""

import sys
import json
import math
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

# Import core confidence engine
from core.confidence_engine import confidence_score, bet_recommendation


def sigmoid(x: float) -> float:
    x = max(-500, min(500, x))
    return 1 / (1 + math.exp(-x))


def clamp(x: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, x))


def poisson_pmf(k: int, lam: float) -> float:
    """Poisson probability mass function"""
    if lam <= 0:
        return 0.0 if k > 0 else 1.0
    if k < 0:
        return 0.0
    try:
        log_pmf = -lam + k * math.log(lam) - math.lgamma(k + 1)
        return math.exp(log_pmf)
    except (ValueError, OverflowError):
        return 0.0


def poisson_over_prob(lam: float, line: float) -> float:
    """Probability of over a given line using Poisson"""
    n = int(math.floor(line))
    return 1 - sum(poisson_pmf(k, lam) for k in range(0, n + 1))


def poisson_at_least_one(lam: float) -> float:
    """Probability of at least one goal"""
    return 1 - math.exp(-lam)


# ============================================================================
# TEAM PROFILES - Estonia Meistriliiga
# ============================================================================

TEAM_PROFILES = {
    "FC Kuressaare": {
        "abbreviation": "KUR",
        "xg_for": 1.25,           # Expected goals for per game
        "xg_against": 1.55,       # Expected goals against per game
        "shots_per_game": 10.5,
        "sot_per_game": 3.8,
        "goals_for_per_game": 1.15,
        "goals_against_per_game": 1.65,
        "clean_sheets_last10": 2,
        "home_record": 0.45,      # Win % at home
        "away_record": 0.25,
        "recent_form": 0.35,      # Win % last 10 games
        "tempo": 0.35,
        "width_crossing": 0.55,
        "final_third_pressure": 0.48,
        "missing_attacker": 0,
        "missing_creator": 0,
        "missing_cb": 0,
        "missing_gk": 0,
        "notes": "Lower-mid table Estonian club. Struggles offensively with below-average xG creation. Defensively leaky. Relies on home pitch for points."
    },
    "Trans Narva": {
        "abbreviation": "NAR",
        "xg_for": 1.35,
        "xg_against": 1.45,
        "shots_per_game": 11.2,
        "sot_per_game": 4.0,
        "goals_for_per_game": 1.25,
        "goals_against_per_game": 1.50,
        "clean_sheets_last10": 3,
        "home_record": 0.40,
        "away_record": 0.30,
        "recent_form": 0.40,      # Win % last 10 games
        "tempo": 0.30,
        "width_crossing": 0.50,
        "final_third_pressure": 0.45,
        "missing_attacker": 0,
        "missing_creator": 1,
        "missing_cb": 0,
        "missing_gk": 0,
        "notes": "Mid-table Estonian club. Slightly better than Kuressaare in attack. Decent defensive structure but lacks creativity. Missing key creator."
    },
}

# Venue info
VENUE_INFO = {
    "Kuressaare linnastaadion": {
        "description": "Home ground of FC Kuressaare. Natural grass, capacity ~2,000. Coastal stadium with occasional wind factor.",
        "home_boost": 1.05,
    }
}

# Estonian Meistriliiga league config
LEAGUE_CONFIG = {
    "avg_goals_per_game": 2.65,
    "goal_variance": 1.02,
    "home_advantage": 0.35,
    "draw_rate": 0.25,
}


def analyze_soccer_match(
    home_team: str,
    away_team: str,
    venue: str,
    date: str = "2026-06-16",
    market_line: float = 0.0,
    market_total: float = 2.5,
    analysis_data: Dict[str, Any] = None,
) -> Dict[str, Any]:
    """
    Comprehensive soccer analysis using xG-based Poisson modeling.
    """
    home_stats = TEAM_PROFILES[home_team]
    away_stats = TEAM_PROFILES[away_team]
    venue_info = VENUE_INFO.get(venue, {})

    generation_time = datetime.now().strftime("%Y-%m-%d %H:%M")
    print("=" * 85)
    print(f"SOCCER MATCH ANALYSIS: {home_team} vs {away_team}")
    print(f"Estonian Meistriliiga - {date}")
    print(f"Venue: {venue} | {venue_info.get('description', '')}")
    print("Generated by MultiSportPredict Engine")
    print(f"Timestamp: {generation_time}")
    print("=" * 85)
    print()

    # ── 1. TEAM STATISTICS ──
    print("1. TEAM STATISTICS (Expected Goals & Metrics)")
    print("-" * 50)
    for label, stats in [(f"  {home_team} (Home):", home_stats), (f"  {away_team} (Away):", away_stats)]:
        print(label)
        print(f"    xG For: {stats['xg_for']:.2f} | xG Against: {stats['xg_against']:.2f}")
        print(f"    Goals For: {stats['goals_for_per_game']:.2f} | Goals Against: {stats['goals_against_per_game']:.2f}")
        print(f"    Shots/Game: {stats['shots_per_game']:.1f} | SOT/Game: {stats['sot_per_game']:.1f}")
        print(f"    Form: {stats['recent_form']:.0%} | Home/Away: {stats['home_record']:.0%}/{stats['away_record']:.0%}")
        print(f"    Clean Sheets (L10): {stats['clean_sheets_last10']}")
        print(f"    Injuries: Attackers={stats['missing_attacker']}, Creators={stats['missing_creator']}, "
              f"CBs={stats['missing_cb']}, GK={stats['missing_gk']}")
        print(f"    Notes: {stats['notes']}")
        print()

    # ── 2. xG ANALYSIS ──
    print("2. xG & MATCHUP ANALYSIS")
    print("-" * 50)
    
    xg_gap = home_stats['xg_for'] - away_stats['xg_for']
    xga_gap = away_stats['xg_against'] - home_stats['xg_against']
    
    # Goal strength scores
    home_strength = (
        1.25 * (home_stats['xg_for'] - 1.35) +
        -0.95 * (home_stats['xg_against'] - 1.25) +
        0.12 * (home_stats['shots_per_game'] - 11) +
        0.18 * (home_stats['sot_per_game'] - 4) +
        0.10 * (home_stats['goals_for_per_game'] - 1.2) +
        -0.10 * (home_stats['goals_against_per_game'] - 1.1) +
        0.25 * home_stats['tempo'] +
        0.20 * 1 +  # Home advantage
        -0.30 * home_stats['missing_attacker'] +
        -0.22 * home_stats['missing_creator'] +
        0.24 * (home_stats['missing_cb'] + home_stats['missing_gk'])
    )
    
    away_strength = (
        1.25 * (away_stats['xg_for'] - 1.35) +
        -0.95 * (away_stats['xg_against'] - 1.25) +
        0.12 * (away_stats['shots_per_game'] - 11) +
        0.18 * (away_stats['sot_per_game'] - 4) +
        0.10 * (away_stats['goals_for_per_game'] - 1.2) +
        -0.10 * (away_stats['goals_against_per_game'] - 1.1) +
        0.25 * away_stats['tempo'] +
        0.20 * 0 +  # Away
        -0.30 * away_stats['missing_attacker'] +
        -0.22 * away_stats['missing_creator'] +
        0.24 * (away_stats['missing_cb'] + away_stats['missing_gk'])
    )
    
    print(f"    xG For Gap: {xg_gap:+.2f} (Favors {home_team if xg_gap > 0 else away_team})")
    print(f"    xG Against Gap: {xga_gap:+.2f} (Favors {home_team if xga_gap > 0 else away_team})")
    print(f"    Home Goal Strength: {home_strength:+.2f}")
    print(f"    Away Goal Strength: {away_strength:+.2f}")
    print()

    # ── 3. GOAL PROJECTIONS (Poisson) ──
    print("3. GOAL PROJECTIONS (Poisson xG Model)")
    print("-" * 50)

    # Estimate expected goals (lambda)
    home_lam = (
        0.55 * home_stats['xg_for'] +
        0.30 * away_stats['xg_against'] +
        0.15 * home_stats['sot_per_game'] / 4.0 +
        0.10 * home_stats['tempo'] +
        0.10 * 1.0 +  # Home advantage
        -0.15 * home_stats['missing_attacker'] +
        -0.10 * home_stats['missing_creator'] +
        0.12 * (away_stats['missing_cb'] + away_stats['missing_gk'])
    )
    # Apply league variance and home advantage
    home_lam *= LEAGUE_CONFIG['goal_variance']
    home_lam *= (1 + LEAGUE_CONFIG['home_advantage'] * 0.1)
    
    away_lam = (
        0.55 * away_stats['xg_for'] +
        0.30 * home_stats['xg_against'] +
        0.15 * away_stats['sot_per_game'] / 4.0 +
        0.10 * away_stats['tempo'] +
        0.10 * 0.0 +  # No home advantage
        -0.15 * away_stats['missing_attacker'] +
        -0.10 * away_stats['missing_creator'] +
        0.12 * (home_stats['missing_cb'] + home_stats['missing_gk'])
    )
    away_lam *= LEAGUE_CONFIG['goal_variance']
    
    total_lam = home_lam + away_lam

    # Compute match outcome probabilities using bivariate Poisson
    max_goals = 6
    home_win_prob = 0.0
    draw_prob = 0.0
    away_win_prob = 0.0
    
    for i in range(max_goals + 1):
        for j in range(max_goals + 1):
            p = poisson_pmf(i, home_lam) * poisson_pmf(j, away_lam)
            if i > j:
                home_win_prob += p
            elif i == j:
                draw_prob += p
            else:
                away_win_prob += p
    
    total_prob = home_win_prob + draw_prob + away_win_prob
    if total_prob > 0:
        home_win_prob /= total_prob
        draw_prob /= total_prob
        away_win_prob /= total_prob

    # Apply league draw rate adjustment
    draw_prob = draw_prob * 0.8 + LEAGUE_CONFIG['draw_rate'] * 0.2
    remaining = 1 - draw_prob
    home_win_prob = home_win_prob * remaining / (home_win_prob + away_win_prob + 0.001)
    away_win_prob = 1 - home_win_prob - draw_prob

    print(f"    {home_team} xG (lambda): {home_lam:.2f}")
    print(f"    {away_team} xG (lambda): {away_lam:.2f}")
    print(f"    Total xG: {total_lam:.2f}")
    print(f"    Projected Score: {home_team} {home_lam:.1f} - {away_team} {away_lam:.1f}")
    print()

    # ── 4. GOAL LINE PROBABILITIES ──
    print("4. GOAL LINE PROBABILITIES (Poisson)")
    print("-" * 50)
    
    p_over_15 = poisson_over_prob(total_lam, 1.5)
    p_over_25 = poisson_over_prob(total_lam, 2.5)
    p_over_35 = poisson_over_prob(total_lam, 3.5)
    p_over_45 = poisson_over_prob(total_lam, 4.5)
    
    print(f"    Over 1.5 Goals: {p_over_15:.1%}")
    print(f"    Over 2.5 Goals: {p_over_25:.1%}")
    print(f"    Over 3.5 Goals: {p_over_35:.1%}")
    print(f"    Over 4.5 Goals: {p_over_45:.1%}")
    
    # Total recommendation
    totals_edge = total_lam - market_total
    total_conf = confidence_score(totals_edge, volatility=0.50)
    total_lean = "Over" if totals_edge > 0 else "Under"
    
    # Determine over probability at market total
    if market_total <= 1.5:
        totals_prob = p_over_15
    elif market_total <= 2.5:
        totals_prob = p_over_25
    elif market_total <= 3.5:
        totals_prob = p_over_35
    else:
        totals_prob = p_over_45
    
    if totals_prob >= 0.57:
        total_rec = f"Over {market_total}"
    elif totals_prob <= 0.43:
        total_rec = f"Under {market_total}"
    else:
        total_rec = "Pass"
    
    print(f"    Market Total: {market_total}")
    print(f"    Model Total: {total_lam:.2f}")
    print(f"    Edge: {totals_edge:+.2f}")
    print(f"    Lean: {total_lean} (Conf: {total_conf:.1f}%)")
    print(f"    Recommendation: {total_rec}")
    print()

    # ── 5. MATCH OUTCOME ──
    print("5. MATCH OUTCOME PROBABILITY")
    print("-" * 50)
    
    print(f"    {home_team} Win: {home_win_prob:.1%}")
    print(f"    Draw: {draw_prob:.1%}")
    print(f"    {away_team} Win: {away_win_prob:.1%}")
    
    # Moneyline / Double Chance
    ml_edge = abs(home_win_prob - 0.5) * 100
    ml_conf = confidence_score(ml_edge, volatility=0.45)
    
    if home_win_prob >= 0.57:
        ml_rec = f"Moneyline {home_team}"
    elif away_win_prob >= 0.57:
        ml_rec = f"Moneyline {away_team}"
    else:
        ml_rec = "Pass (consider Double Chance)"
    
    print(f"    ML Edge: {ml_edge:.1f}% | Conf: {ml_conf:.1f}%")
    print(f"    Recommendation: {ml_rec}")
    print()

    # ── 6. BTTS (Both Teams To Score) ──
    print("6. BTTS ANALYSIS")
    print("-" * 50)
    
    home_scores_prob = poisson_at_least_one(home_lam)
    away_scores_prob = poisson_at_least_one(away_lam)
    btts_prob_raw = home_scores_prob * away_scores_prob
    
    # Structural BTTS strength
    home_btts_strength = (
        1.05 * (home_stats['xg_for'] - 1.20) +
        0.95 * (home_stats['xg_against'] - 1.25) +
        0.10 * (home_stats['goals_for_per_game'] - 1.2) +
        0.10 * (home_stats['goals_against_per_game'] - 1.1) +
        0.12 * (home_stats['sot_per_game'] - 3.5) +
        0.18 * home_stats['tempo'] +
        0.15 * home_stats['final_third_pressure'] +
        -0.35 * home_stats['missing_attacker'] +
        0.28 * (home_stats['missing_cb'] + home_stats['missing_gk']) +
        -0.20 * home_stats['clean_sheets_last10'] / 10.0
    )
    away_btts_strength = (
        1.05 * (away_stats['xg_for'] - 1.20) +
        0.95 * (away_stats['xg_against'] - 1.25) +
        0.10 * (away_stats['goals_for_per_game'] - 1.2) +
        0.10 * (away_stats['goals_against_per_game'] - 1.1) +
        0.12 * (away_stats['sot_per_game'] - 3.5) +
        0.18 * away_stats['tempo'] +
        0.15 * away_stats['final_third_pressure'] +
        -0.35 * away_stats['missing_attacker'] +
        0.28 * (away_stats['missing_cb'] + away_stats['missing_gk']) +
        -0.20 * away_stats['clean_sheets_last10'] / 10.0
    )
    
    structural = sigmoid((home_btts_strength + away_btts_strength) / 2.0)
    btts_prob = clamp(0.45 * structural + 0.55 * btts_prob_raw)
    
    btts_edge = btts_prob - 0.5
    btts_conf = confidence_score(btts_edge * 100, volatility=0.48)
    btts_rec = "PASS"
    if btts_prob >= 0.57:
        btts_rec = "Yes BTTS"
    elif btts_prob <= 0.43:
        btts_rec = "No BTTS"
    
    print(f"    Home Scores Prob: {home_scores_prob:.1%}")
    print(f"    Away Scores Prob: {away_scores_prob:.1%}")
    print(f"    BTTS Probability: {btts_prob:.1%}")
    print(f"    Edge: {btts_edge:+.1%}")
    print(f"    Confidence: {btts_conf:.1f}%")
    print(f"    Recommendation: {btts_rec}")
    print()

    # ── 7. SHARP CONSENSUS ──
    print("7. SHARP CONSENSUS & MARKET LEAN")
    print("-" * 50)
    if analysis_data:
        for key, value in analysis_data.items():
            if key == "sharp_lean":
                print(f"    MARKET LEAN: {value}")
            elif key == "prop_angle":
                print(f"    PROP ANGLE: {value}")
            else:
                print(f"    {key.upper()}: {value}")
    print()

    # ── 8. CORNER PROJECTION ──
    print("8. CORNER PROJECTION")
    print("-" * 50)
    
    home_corner_strength = (
        0.28 * (home_stats['shots_per_game'] - 12) +
        0.18 * (home_stats['sot_per_game'] - 4) +
        0.90 * home_stats['final_third_pressure'] +
        0.75 * home_stats['width_crossing'] +
        0.25 * home_stats['tempo'] +
        0.30 * 1 +
        0.25 * (home_stats['missing_cb'] + home_stats['missing_gk']) +
        -0.20 * home_stats['missing_attacker']
    )
    away_corner_strength = (
        0.28 * (away_stats['shots_per_game'] - 12) +
        0.18 * (away_stats['sot_per_game'] - 4) +
        0.90 * away_stats['final_third_pressure'] +
        0.75 * away_stats['width_crossing'] +
        0.25 * away_stats['tempo'] +
        0.30 * 0 +
        0.25 * (away_stats['missing_cb'] + away_stats['missing_gk']) +
        -0.20 * away_stats['missing_attacker']
    )
    
    corner_total = 9.2 + 0.75 * (home_corner_strength + away_corner_strength)
    corner_total = max(4.0, corner_total)
    
    print(f"    Projected Total Corners: {corner_total:.1f}")
    print()

    # ── 9. FINAL RECOMMENDATIONS ──
    print("9. FINAL RECOMMENDATIONS")
    print("-" * 50)
    print(f"    MATCH OUTCOME: {ml_rec} (Conf: {ml_conf:.1f}%)")
    print(f"    TOTAL (O/U {market_total}): {total_rec} (Conf: {total_conf:.1f}%)")
    print(f"    BTTS: {btts_rec} (Conf: {btts_conf:.1f}%)")
    print(f"    PROJECTED: {home_team} {home_lam:.1f} - {away_team} {away_lam:.1f}")
    print(f"    WIN PROB: {home_team} {home_win_prob:.1%} | Draw {draw_prob:.1%} | {away_team} {away_win_prob:.1%}")
    if analysis_data and "sharp_lean" in analysis_data:
        print(f"    SHARP LEAN: {analysis_data['sharp_lean']}")
    print()
    print("=" * 85)

    # Build result dict
    result = {
        "sport": "soccer",
        "league": "Estonian Meistriliiga",
        "matchup": f"{home_team} vs {away_team}",
        "venue": venue,
        "date": date,
        "generated_at": generation_time,
        "home_team": {
            "name": home_team,
            "abbreviation": home_stats["abbreviation"],
            "stats": home_stats,
        },
        "away_team": {
            "name": away_team,
            "abbreviation": away_stats["abbreviation"],
            "stats": away_stats,
        },
        "projections": {
            "home_xg": round(home_lam, 2),
            "away_xg": round(away_lam, 2),
            "total_xg": round(total_lam, 2),
            "home_projected_goals": round(home_lam, 1),
            "away_projected_goals": round(away_lam, 1),
        },
        "match_outcome": {
            "home_win_prob": round(home_win_prob, 4),
            "draw_prob": round(draw_prob, 4),
            "away_win_prob": round(away_win_prob, 4),
            "ml_rec": ml_rec,
            "ml_confidence": round(ml_conf, 1),
        },
        "totals_analysis": {
            "model_total": round(total_lam, 2),
            "market_total": market_total,
            "edge": round(totals_edge, 2),
            "over_probability": round(totals_prob, 4),
            "confidence": round(total_conf, 1),
            "recommendation": total_rec,
            "lean": total_lean,
            "over_15": round(p_over_15, 4),
            "over_25": round(p_over_25, 4),
            "over_35": round(p_over_35, 4),
        },
        "btts_analysis": {
            "probability": round(btts_prob, 4),
            "edge": round(btts_edge, 4),
            "confidence": round(btts_conf, 1),
            "recommendation": btts_rec,
        },
        "corner_projection": {
            "total_corners": round(corner_total, 1),
        },
        "sharp_consensus": analysis_data or {},
    }

    return result


def main():
    output_dir = Path("output/soccer")
    output_dir.mkdir(parents=True, exist_ok=True)

    # ──────────────────────────────────────────────────────────────────────
    # MATCHUP: FC Kuressaare (Home) vs Trans Narva (Away)
    # Venue: Kuressaare linnastaadion
    # League: Estonian Meistriliiga
    # ──────────────────────────────────────────────────────────────────────
    print("\n" + "=" * 100)
    print("ESTONIAN MEISTRILIIGA: FC Kuressaare vs Trans Narva")
    print("=" * 100)

    analysis_data = {
        "sharp_lean": "Under 2.5 Goals (Both teams below average xG)",
        "prop_angle": "N/A - Low liquidity market, no reliable player props",
        "venue": "Kuressaare linnastaadion",
        "league_notes": "Estonian Meistriliiga - Moderate scoring league (~2.65 goals/match). Lower liquidity market.",
        "keyMatchup": "Two bottom-half teams. Neither generates high-quality chances. Trans Narva missing key creator.",
        "homeAdvantage": "Kuressaare relies heavily on home form (45% home win rate vs 25% away). Coastal stadium factor.",
        "fatigueFactor": "Both teams on normal rest. No major travel concerns.",
        "sharpReasoning": "Both teams have below-average xG creation. Narva missing creative midfielder. Expect a tight, low-scoring affair typical of mid-table Meistriliiga clashes.",
    }

    result = analyze_soccer_match(
        home_team="FC Kuressaare",
        away_team="Trans Narva",
        venue="Kuressaare linnastaadion",
        date="2026-06-16",
        market_line=0.0,
        market_total=2.5,
        analysis_data=analysis_data,
    )

    # Save to file
    out_path = output_dir / "fc_kuressaare_vs_trans_narva_analysis.json"
    with open(out_path, 'w') as f:
        json.dump(result, f, indent=2, default=str)
    print(f"\nResults saved to: {out_path}")

    # ──────────────────────────────────────────────────────────────────────
    # SUMMARY
    # ──────────────────────────────────────────────────────────────────────
    print("\n\n" + "=" * 100)
    print("ESTONIAN MEISTRILIIGA - JUNE 16, 2026 ANALYSIS SUMMARY")
    print("=" * 100)
    print()
    r = result
    print(f"MATCHUP: {r['home_team']['name']} vs {r['away_team']['name']}")
    print(f"    Projected: {r['home_team']['name']} {r['projections']['home_projected_goals']:.1f} - "
          f"{r['away_team']['name']} {r['projections']['away_projected_goals']:.1f}")
    print(f"    Total xG: {r['projections']['total_xg']:.2f}")
    print(f"    Win Prob: {r['home_team']['name']} {r['match_outcome']['home_win_prob']:.1%} | "
          f"Draw {r['match_outcome']['draw_prob']:.1%} | "
          f"{r['away_team']['name']} {r['match_outcome']['away_win_prob']:.1%}")
    print()
    print(f"    MATCH OUTCOME: {r['match_outcome']['ml_rec']} (Conf: {r['match_outcome']['ml_confidence']:.1f}%)")
    print(f"    TOTAL: {r['totals_analysis']['recommendation']} (Conf: {r['totals_analysis']['confidence']:.1f}%)")
    print(f"    BTTS: {r['btts_analysis']['recommendation']} (Conf: {r['btts_analysis']['confidence']:.1f}%)")
    print(f"    SHARP LEAN: {r['sharp_consensus']['sharp_lean']}")
    print()
    print("=" * 100)


if __name__ == "__main__":
    main()